import { type HeadComponent } from "next13/head";

const Head: HeadComponent = () => {
  return (
    <>
      <title>Create Next App</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by Create Next App" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
};

export default Head;
